		window.addEventListener('load',function(){
			var aboutOffset = $('#about').offset().top;
			var eventOffset = $('#events').offset().top;
			var splOffset = $('.eventSpl').offset().top;
			var contactOffset = $('.contact_us').offset().top;
			var committeeOffset = $('#committee').offset().top;
			var sOffset = $(window).scrollTop();
			if(sOffset>=splOffset-300)
			{
				$('.eventSpl').css('visibility','inherit');
				$('.eventSpl').addClass('fadeIn');
				$('.spl_text').css('visibility','inherit');
				$('.spl_text').addClass('slideInDown');
			}
			if(sOffset>=contactOffset-250)
			{
				$('.contact_us').css('visibility','inherit');
				$('.contact_us').addClass('slideInUp');	
			}
			var m = window.matchMedia( "(max-width: 768px)" );
			if(m.matches){
				if(sOffset>=aboutOffset)
				{
					$('#about').css('visibility','inherit');
					$('#about').addClass('fadeIn');
				}
				if(sOffset>=aboutOffset)
				{
					$('.about-1').css('visibility','inherit');
					$('.about-1').addClass('bounceInLeft');
					$('.about-img-1').css('visibility','inherit');
					$('.about-img-1').addClass('bounceInRight');	
				}
				if(sOffset>=aboutOffset+150)
				{
					$('.about-2').css('visibility','inherit');
					$('.about-2').addClass('fadeInUp');	
				}
				if(sOffset>=eventOffset-300)
				{
					$('.event1').css('visibility','inherit');
					$('.event1').addClass('fadeInLeft');
					$('.event2').css('visibility','inherit');
					$('.event2').addClass('fadeInRight');
				}
				if(sOffset>=eventOffset+50)
				{
					$('.event3').css('visibility','inherit');
					$('.event3').addClass('fadeInLeft');
					$('.event4').css('visibility','inherit');
					$('.event4').addClass('fadeInRight');
				}
				if(sOffset>=eventOffset+780)
				{
					$('.event5').css('visibility','inherit');
					$('.event5').addClass('fadeInLeft');
					$('.event6').css('visibility','inherit');
					$('.event6').addClass('fadeInRight');
				}
				if(sOffset>=eventOffset+950)
				{
					$('.event7').css('visibility','inherit');
					$('.event7').addClass('fadeInLeft');
				}
				if(sOffset>=committeeOffset-200)
				{
					$('.row_1').css('visibility','inherit');
					$('.row_1').addClass('zoomIn');
				}
				if(sOffset>=committeeOffset+320)
				{
					$('.row_2').css('visibility','inherit');
					$('.row_2').addClass('zoomIn');	
				}
				if(sOffset>=committeeOffset+675)
				{
					$('.row_3').css('visibility','inherit');
					$('.row_3').addClass('zoomIn');		
				}
			}
			else
			{
				if(sOffset>=aboutOffset-250)
				{
					$('#about').css('visibility','inherit');
					$('#about').addClass('fadeIn');
				}
				if(sOffset>=aboutOffset-200)
				{
					$('.about-1').css('visibility','inherit');
					$('.about-1').addClass('bounceInLeft');
					$('.about-img-1').css('visibility','inherit');
					$('.about-img-1').addClass('bounceInRight');	
				}
				if(sOffset>=aboutOffset-100)
				{
					$('.about-2').css('visibility','inherit');
					$('.about-2').addClass('fadeInUp');	
				}
				if(sOffset>=committeeOffset-200)
				{
					$('.row_1').css('visibility','inherit');
					$('.row_1').addClass('zoomIn');
					$('.row_2').css('visibility','inherit');
					$('.row_2').addClass('zoomIn');
					$('.row_3').css('visibility','inherit');
					$('.row_3').addClass('zoomIn');		
				}
				if(sOffset>=eventOffset-200)
				{

					$('.event1').css('visibility','inherit');
					$('.event1').addClass('fadeInDown');
					$('.event2').css('visibility','inherit');
					$('.event2').addClass('fadeInDown');
					$('.event3').css('visibility','inherit');
					$('.event3').addClass('fadeInDown');
					$('.event4').css('visibility','inherit');
					$('.event4').addClass('fadeInDown');
					$('.event5').css('visibility','inherit');
					$('.event5').addClass('fadeInUp');
					$('.event6').css('visibility','inherit');
					$('.event6').addClass('fadeInUp');
					$('.event7').css('visibility','inherit');
					$('.event7').addClass('fadeInUp');
				}
			}	
		});
		$(document).ready(function(){
			var aboutOffset = $('#about').offset().top;
			var eventOffset = $('#events').offset().top;
			var splOffset = $('.eventSpl').offset().top;
			var contactOffset = $('.contact_us').offset().top;
			var committeeOffset = $('#committee').offset().top;
			$(window).scroll(function(){
				var sOffset = $(window).scrollTop();
				if(sOffset>=splOffset-300)
				{
					$('.eventSpl').css('visibility','inherit');
					$('.eventSpl').addClass('fadeIn');
					$('.spl_text').css('visibility','inherit');
					$('.spl_text').addClass('slideInDown');
				}
				if(sOffset>=contactOffset-250)
				{
					$('.contact_us').css('visibility','inherit');
					$('.contact_us').addClass('slideInUp');	
				}

				var m = window.matchMedia( "(max-width: 768px)" );
			if(m.matches){
				if(sOffset>=aboutOffset-150)
				{
					$('#about').css('visibility','inherit');
					$('#about').addClass('fadeIn');
				}
				if(sOffset>=aboutOffset-100)
				{
					$('.about-1').css('visibility','inherit');
					$('.about-1').addClass('bounceInLeft');
					$('.about-img-1').css('visibility','inherit');
					$('.about-img-1').addClass('bounceInRight');	
				}
				if(sOffset>=aboutOffset+150)
				{
					$('.about-2').css('visibility','inherit');
					$('.about-2').addClass('fadeInUp');	
				}
				if(sOffset>=eventOffset-300)
				{
					$('.event1').css('visibility','inherit');
					$('.event1').addClass('fadeInLeft');
					$('.event2').css('visibility','inherit');
					$('.event2').addClass('fadeInRight');
				}
				if(sOffset>=eventOffset+50)
				{
					$('.event3').css('visibility','inherit');
					$('.event3').addClass('fadeInLeft');
					$('.event4').css('visibility','inherit');
					$('.event4').addClass('fadeInRight');
				}
				if(sOffset>=eventOffset+780)
				{
					$('.event5').css('visibility','inherit');
					$('.event5').addClass('fadeInLeft');
					$('.event6').css('visibility','inherit');
					$('.event6').addClass('fadeInRight');
				}
				if(sOffset>=eventOffset+950)
				{
					$('.event7').css('visibility','inherit');
					$('.event7').addClass('fadeInLeft');
				}
				if(sOffset>=committeeOffset-200)
				{
					$('.row_1').css('visibility','inherit');
					$('.row_1').addClass('zoomIn');
				}
				if(sOffset>=committeeOffset+320)
				{
					$('.row_2').css('visibility','inherit');
					$('.row_2').addClass('zoomIn');	
				}
				if(sOffset>=committeeOffset+675)
				{
					$('.row_3').css('visibility','inherit');
					$('.row_3').addClass('zoomIn');		
				}
			}
			else
			{
				if(sOffset>=aboutOffset-250)
				{
					$('#about').css('visibility','inherit');
					$('#about').addClass('fadeIn');
				}
				if(sOffset>=aboutOffset-200)
				{
					$('.about-1').css('visibility','inherit');
					$('.about-1').addClass('bounceInLeft');
					$('.about-img-1').css('visibility','inherit');
					$('.about-img-1').addClass('bounceInRight');	
				}
				if(sOffset>=aboutOffset-100)
				{
					$('.about-2').css('visibility','inherit');
					$('.about-2').addClass('fadeInUp');	
				}
				if(sOffset>=committeeOffset-200)
				{
					$('.row_1').css('visibility','inherit');
					$('.row_1').addClass('zoomIn');
					$('.row_2').css('visibility','inherit');
					$('.row_2').addClass('zoomIn');
					$('.row_3').css('visibility','inherit');
					$('.row_3').addClass('zoomIn');		
				}
				if(sOffset>=eventOffset-200)
				{

					$('.event1').css('visibility','inherit');
					$('.event1').addClass('fadeInDown');
					$('.event2').css('visibility','inherit');
					$('.event2').addClass('fadeInDown');
					$('.event3').css('visibility','inherit');
					$('.event3').addClass('fadeInDown');
					$('.event4').css('visibility','inherit');
					$('.event4').addClass('fadeInDown');
					$('.event5').css('visibility','inherit');
					$('.event5').addClass('fadeInUp');
					$('.event6').css('visibility','inherit');
					$('.event6').addClass('fadeInUp');
					$('.event7').css('visibility','inherit');
					$('.event7').addClass('fadeInUp');
				}
			}
			});
			
		});